---

- include: ./zookeeper.yml

- name: Apache Drill
  hosts: hadoopnodes
  become: yes
  roles:
    - role: drill
      drill_zookeeper_url: "{{ groups['zookeepernodes'] | join(':2181,') ~ ':2181' }}"
