---
- name: Check if MySQL is already installed.
  stat: path=/etc/init.d/mysql
  register: mysql_installed

- name: Update apt cache if MySQL is not yet installed.
  apt: update_cache=yes
  when: mysql_installed.stat.exists == false

- name: Check if MySQL Python libraries are installed.
  apt: "name=python-mysqldb state=installed"

- name: Check if MySQL connector is  installed.
  apt: "name=libmysql-java state=installed"

- name: Install MySQL packages.
  apt: name={{ item }} state=installed update_cache=yes
  with_items: "{{ mysql_pkgs }}"

#- name: Copy the root credentials as .my.cnf file
#  template: src=root.cnf.j2 dest=~/.my.cnf mode=0644
 
- name: Start mysql
  service: 
    name: mysql 
    state: started

- name: Update MySQL root password for all root accounts
  mysql_user: 
    name: "{{ mysql_root_user }}" 
    host: "{{ item }}" 
    password: "{{ mysql_root_pass }}" 
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy the root credentials as .my.cnf file
  template: src=root.cnf.j2 dest=~/.my.cnf mode=0644

- name: Ensure Anonymous user(s) does not exist
  mysql_user: 
    name: '' 
    host: "{{ item }}" 
    state: absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"
  notify: 
    - restart mysql

