---

- name: common
  hosts: all
  become: yes
  tags: common
  roles:

    - role: common

      iface_internal: "{{ bds_internal_iface }}"
      use_ansible_inventory_hostname: true
      generate_hosts_file: true

      package_list_debian:
        - emacs24-nox
        - ssh

      package_list_redhat:
        - emacs-nox
        - openssh-clients

      package_list_common:
        - curl
        - httpie
        - rsync
        - parted
        - iotop
        - facter

      services_running_debian:
        - ssh

      services_running_redhat:
        - sshd

      groups_managed:
        hadoopadmin:
        hadoopuser:


- name: frontend packages
  hosts: frontends
  become: yes
  tags: common
  roles:
    - role: common
      package_list:
        - git
        - unzip
        - maven
